# Generated by Django 5.2.7 on 2025-11-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safezone',
            name='color',
            field=models.CharField(default='#1E8E3E', max_length=7),
        ),
        migrations.AddField(
            model_name='safezone',
            name='polygon_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='safezone',
            name='zone_type',
            field=models.CharField(choices=[('polygon', 'Polígono'), ('circle', 'Círculo')], default='polygon', max_length=20),
        ),
        migrations.AlterField(
            model_name='safezone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='safezone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='safezone',
            name='radius_meters',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
