# Generated by Django 5.2.7 on 2025-12-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('is_in_safe_zone', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de ubicación',
                'verbose_name_plural': 'Historial de ubicaciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('zone_exit', 'Salida de zona'), ('zone_entry', 'Entrada a zona'), ('low_battery', 'Batería baja'), ('device_offline', 'Dispositivo sin conexión')], default='zone_exit', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='is_in_safe_zone',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddIndex(
            model_name='safezone',
            index=models.Index(fields=['child', 'is_active'], name='monitoring__child_i_b9db83_idx'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='monitoring.child'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='monitoring.device'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['device', '-timestamp'], name='monitoring__device__ed86a8_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['child', '-timestamp'], name='monitoring__child_i_bff71b_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['timestamp'], name='monitoring__timesta_4c6aa8_idx'),
        ),
    ]
